version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - gradle build
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - build/libs/todo-0.0.1-SNAPSHOT.jar
  discard-paths: yes